---
name: Build and Release

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - seeed_xiao_rp2040
          - seeed_xiao_rp2040_led
          - esp32_s2_saola
          - esp32_s3_devkit
          - seeed_xiao_esp32c3
          - seeed_xiao_esp32s3
          - seeed_xiao_esp32s3_sense
          - nucleo_f446re
          - seeed_xiao_samd21
          - adafruit_feather_nrf52840
          - adafruit_feather_nrf52832
        example:
          - SineWaveSpeed
        include:
          - platform: seeed_xiao_rp2040
            example: FiftyPercent
          - platform: seeed_xiao_rp2040_led
            example: FiftyPercent
          - platform: seeed_xiao_rp2040
            example: RotaryEncoderWithBEMF
          - platform: seeed_xiao_rp2040_led
            example: RotaryEncoderWithBEMF

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install PlatformIO and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio

      - name: Build Firmware
        env:
          PIOPROJECT_SRC_DIR: examples/${{ matrix.example }}
        run: pio run -e ${{ matrix.platform }}

      - name: Rename Firmware and Set Path
        id: rename
        run: |
          FIRMWARE_BASENAME="xDuinoRails_MotorControl_bEMF-"
          FIRMWARE_BASENAME="${FIRMWARE_BASENAME}${{ matrix.example }}-"
          FIRMWARE_BASENAME="${FIRMWARE_BASENAME}${{ matrix.platform }}"
          BUILD_DIR=".pio/build/${{ matrix.platform }}"

          EXTENSION="bin"
          SUFFIX=""

          if [[ "${{ matrix.platform }}" == "seeed_xiao_rp2040_led" ]]; then
            EXTENSION="uf2"
            SUFFIX="_led"
          elif [[ "${{ matrix.platform }}" == "seeed_xiao_rp2040" ]]; then
            EXTENSION="uf2"
          elif [[ "${{ matrix.platform }}" == *"nrf52"* ]]; then
             if [ -f "${BUILD_DIR}/firmware.zip" ]; then
                EXTENSION="zip"
             else
                EXTENSION="hex"
             fi
          fi

          mv "${BUILD_DIR}/firmware.${EXTENSION}" "${FIRMWARE_BASENAME}${SUFFIX}.${EXTENSION}"
          echo "firmware_glob=${FIRMWARE_BASENAME}${SUFFIX}.*" >> $GITHUB_OUTPUT

      - name: Upload firmware as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-${{ matrix.example }}-firmware
          path: ${{ steps.rename.outputs.firmware_glob }}

  release:
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    needs: build
    permissions:
      contents: write

    steps:
      - name: Download all firmware artifacts
        uses: actions/download-artifact@v4
        with:
          path: firmware

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            firmware/*/*
