---
name: Build and Release

on:
  push:
    branches:
      - '*'
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - seeed_xiao_rp2040
          - seeed_xiao_rp2040_led
          - esp32_s2_saola
          - esp32_s3_devkit
          - seeed_xiao_esp32c3
          - nucleo_f446re
          - seeed_xiao_samd21
        example:
          - FiftyPercent
          - RotaryEncoderWithBEMF
          - SineWaveSpeed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install PlatformIO and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio

      - name: Build Firmware
        env:
          PIOPROJECT_SRC_DIR: examples/${{ matrix.example }}
        run: pio run -e ${{ matrix.platform }}

      - name: Rename Firmware and Set Path
        id: rename
        run: |
          FIRMWARE_BASENAME="xDuinoRails_MotorControl_bEMF-"
          FIRMWARE_BASENAME="${FIRMWARE_BASENAME}${{ matrix.example }}-"
          FIRMWARE_BASENAME="${FIRMWARE_BASENAME}${{ matrix.platform }}"
          BUILD_DIR=".pio/build/${{ matrix.platform }}"
          if [[ "${{ matrix.platform }}" == "seeed_xiao_rp2040_led" ]]; then
            mv "${BUILD_DIR}/firmware.uf2" "${FIRMWARE_BASENAME}_led.uf2"
          elif [ "${{ matrix.platform }}" == "seeed_xiao_rp2040" ]; then
            mv "${BUILD_DIR}/firmware.uf2" "${FIRMWARE_BASENAME}.uf2"
          else
            mv "${BUILD_DIR}/firmware.bin" "${FIRMWARE_BASENAME}.bin"
          fi
          if [[ "${{ matrix.platform }}" == "seeed_xiao_rp2040_led" ]]; then
            echo "firmware_glob=${FIRMWARE_BASENAME}_led.*" >> $GITHUB_OUTPUT
          else
            echo "firmware_glob=${FIRMWARE_BASENAME}.*" >> $GITHUB_OUTPUT
          fi

      - name: Upload firmware as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-${{ matrix.example }}-firmware
          path: ${{ steps.rename.outputs.firmware_glob }}

  release:
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    needs: build
    permissions:
      contents: write

    steps:
      - name: Download all firmware artifacts
        uses: actions/download-artifact@v4
        with:
          path: firmware

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            firmware/*/*
